---
#
# Author: Aniruddha Gokhale
# CS4287/5287 Principles of Cloud Computing
# Created: Fall 2024
#
# Purpose:
#   This playbook can be used if you would like to try doing
#   the actions from the master playbook step by step. Simply
#   copy the next play from the master to here and execute
#   just this play and make sure it is working. If everything
#   works correctly, you may then terminate your VMs once again
#   and just run the master playbook end to end
#

#####################################################
### Play 4: Install Packages on Cloud VMs
# This play installs all the necessary packages for Docker,
# Kubernetes, and other dependencies.
#####################################################

- name: "Play 4 - Install various packages on Cloud VMs"
  hosts: CloudVMs # Specified in the Inventory file
  remote_user: "{{ cloud_user }}" # Use the cloud user for these VMs
  become: true # Use sudo privileges for installations
  gather_facts: no
  collections:
    - ansible-base

  tasks:
    # Import child playbooks for APT and PIP package installations.
    - import_tasks: tasks/playbook_install_apt_packages.yaml
    - import_tasks: tasks/playbook_install_pip_packages.yaml

#####################################################
### Play 5: Install Docker on Cloud VMs
#####################################################

- name: "Play 5 - Install Docker on Cloud VMs"
  hosts: CloudVMs # Specified in the Inventory file
  remote_user: "{{ cloud_user }}" # Use the cloud user
  gather_facts: yes # We need to gather system information like architecture and OS release
  become: true # Use sudo privileges
  collections:
    - ansible-base

  tasks:
    # Import the child playbook for Docker installation.
    - import_tasks: tasks/playbook_install_docker.yaml

#####################################################
### Play 6: Set up Private Docker Registry on Master VM
#####################################################

- name: "Play 6 - Set up Private Docker Registry on Master VM"
  hosts: k8s-master # Only run on the master VM
  remote_user: "{{ cloud_user }}" # Use the cloud user
  become: true # Use sudo privileges
  gather_facts: no

  tasks:
    # Import the child playbook to set up the Docker registry.
    - import_tasks: tasks/playbook_registry_setup.yaml

#####################################################
### Play 7: Disable Swap on All VMs
# Kubernetes requires swap to be disabled on all nodes.
#####################################################

- name: "Play 7 - Disable Swap on All VMs"
  hosts: CloudVMs # Run on all VMs
  remote_user: "{{ cloud_user }}" # Use the cloud user
  become: true # Use sudo privileges
  gather_facts: no

  tasks:
    # Import the child playbook to disable swap.
    - import_tasks: tasks/playbook_disable_swap.yaml

#####################################################
### Play 8: Set Firewalld Rules
# Configure the firewall to allow traffic for Kubernetes.
#####################################################

- name: "Play 8 - Handle Firewalld Policies"
  hosts: CloudVMs # Run on all VMs
  remote_user: "{{ cloud_user }}" # Use the cloud user
  become: true # Use sudo privileges
  gather_facts: false
  collections:
    - ansible-base
    - community.general

  tasks:
    # Import the child playbook to configure the firewall.
    - import_tasks: tasks/playbook_set_firewalld_rules.yaml

#####################################################
### Play 9: Download and Install Kafka
#####################################################

- name: "Play 9a - Download Kafka Locally"
  hosts: LocalMC # Run on the local machine
  remote_user: "{{ local_user }}" # Use the local user
  gather_facts: no
  become: false # No need for sudo privileges

  tasks:
    # Import the child playbook to download Kafka.
    - import_tasks: tasks/playbook_download_kafka.yaml

- name: "Play 9b - Install Kafka on Cloud VMs"
  hosts: CloudVMs # Run on all cloud VMs
  remote_user: "{{ cloud_user }}" # Use the cloud user
  become: true # Use sudo privileges
  gather_facts: no

  tasks:
    # Import the child playbook to install Kafka.
    - import_tasks: tasks/playbook_install_kafka.yaml
