---
- name: Install required APT packages for Docker and Kubernetes
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
      - lsb-release
      - gpg
      - python3-pip
    state: present
    update_cache: yes

## NEW SECTION DONT RUN THIS AGAIN BECUASE IT WILL OVERWRITE THE EXISTING CONFIGURATION
- name: Ensure /etc/apt/keyrings directory exists with mode 755
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download and dearmor Kubernetes GPG key
  shell: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"

- name: Add Kubernetes apt repository
  shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

- name: refresh apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name: ["kubelet", "kubeadm", "kubectl"]
    state: present
    update_cache: yes

- name: Hold kubelet, kubeadm, and kubectl packages
  command: apt-mark hold kubelet kubeadm kubectl

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: true
    state: started

- name: Add IPv4 forwarding rule
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: "net.ipv4.ip_forward = 1\n"

- name: Reload sysctl
  command: sysctl --system
  become: yes
